# daily_migration:
#  cron: "0 7-24 * * 1-7"
#  queue: cron
#  class: ControlUpload
#  args: "daily_migration"
#  description: migrate sales_report
#  rails_envs: development, production, staging

#jde_test_import:
#   cron: "40 14 * * *"
#   queue: cron
#   class: ControlUpload
#   args: "test_import"
#   description: testing
#   rails_envs: development, production, staging


# DONT CHANGE!!!! FIXED!!! ###########################
  
warehouse_stock:
  cron: "1 0 * * *"
  queue: cron
  class: ControlUpload
  args: "import_stock"
  description: fetching all masters
  rails_envs: development, production, staging
  
warehouse_order:
  cron: "2 0 * * *"
  queue: cron
  class: ControlUpload
  args: "import_orders"
  description: fetching all masters
  rails_envs: development, production, staging
  
jde_masters:
  cron: "3 0 * * *"
  queue: cron
  class: ControlUpload
  args: "import_masters"
  description: fetching all masters
  rails_envs: development, production, staging

jde_intransit_to_pos:
  cron: "0 6,9,13,16,18 * * *"
  queue: cron
  class: ControlUpload
  args: "intransit_pos"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_sales_yesterday:
  cron: "0 6 * * *"
  queue: cron
  class: ControlUpload
  args: "import_sales_jde_yesterday"
  description: intransit jde to point of sales
  rails_envs: development, production, staging

jde_import_sales_today:
  cron: "10 12 * * *"
  queue: cron
  class: ControlUpload
  args: "import_sales_jde_today"
  description: intransit jde to point of sales
  rails_envs: development, production, staging

jde_import_foam_sales:
  cron: "0 8 * * *"
  queue: cron
  class: ControlUpload
  args: "import_sales_foam_jde"
  description: import sales foam from jde to sales analytic
  rails_envs: development, production, staging
  
jde_import_stock_daily:
  cron: "0 2 * * *"
  queue: cron
  class: ControlUpload
  args: "import_stock_daily"
  description: import stock daily
  rails_envs: development, production, staging
  
jde_order_buffer:
  cron: "5 6 * * *"
  queue: cron
  class: ControlUpload
  args: "generate_order_buffer"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
leadtime_delivery:
  cron: "0 0 1 * *"
  queue: cron
  class: ControlUpload
  args: "leadtime_batch"
  description: leadtime delivery from production branch
  rails_envs: development, production, staging
  
  
#jde_import_credit_note:
#  cron: "0 6 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "import_credit_note"
#  description: fetching credit note
#  rails_envs: development, production, staging
  
#jde_import_stock_hourly:
#  cron: "*/5 * * * *"
#  queue: cron
#  class: ControlUpload
#  args: "import_stock_hourly"
#  description: intransit jde to point of sales
#  rails_envs: development, production, staging
#
   
#jde_import_stock_weekly:
#  cron: "0 2 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "import_stock_weekly"
#  description: intransit jde to point of sales
#  rails_envs: development, production, staging

#jde_import_stock_hourly_display:
#  cron: "0 17 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "import_stock_hourly_display"
#  description: import hourly display
#  rails_envs: development, production, staging
#   
#####################################################

########################### PPC

jde_planning_order:
  cron: "0 2 * * *"
  queue: cron
  class: ControlUpload
  args: "planning_order"
  description: import program for ppc
  rails_envs: development, production, staging
  
jde_generate_planning_order:
  cron: "5 6 * * *"
  queue: cron
  class: ControlUpload
  args: "generate_planning_production"
  description: import program for ppc
  rails_envs: development, production, staging
  
########################## END PPC
  
# jde_base_price:
  # cron: "1 0 1 * *"
  # queue: cron
  # class: ControlUpload
  # args: "import_base_prices"
  # description: fetching base prices
  # rails_envs: development, production, staging
#   
# jde_weekly_fetch_on_sunday:
  # cron: "0 21 * * 0"
  # queue: cron
  # class: ControlUpload
  # args: "sunday_weekly_batch"
  # description: fetching item costs and buffer
  # rails_envs: development, production, staging
  
# jde_import_beginning_of_week:
  # cron: "1 0 1 * *"
  # queue: cron
  # class: ControlUpload
  # args: "import_beginning_of_week"
  # description: intransit jde to point of sales
  # rails_envs: development, production, staging
#   
# jde_import_acc_receivable:
 # cron: "30 5 * * *"
 # queue: cron
 # class: ControlUpload
 # args: "import_acc_receivable"
 # description: fetching data A/R
 # rails_envs: development, production, staging
#  
  
weekly_calculation:
  cron: "0 9 * * MON"
  queue: cron
  class: ControlUpload
  args: "weekly_process"
  description: calculate rkm
  rails_envs: development, production, staging
  
monthly_calculation:
  cron: "0 0 1 * *"
  queue: cron
  class: ControlUpload
  args: "monthly_process"
  description: monthly process
  rails_envs: development, production, staging

jde_mailer_order_confirmation:
  cron: "0 5 * * *"
  queue: cron
  class: ControlUpload
  args: "mailer_confirmation_order"
  description: Mail Confirmation Order
  rails_envs: development, production, staging

rkm_weekly_calculation:
  cron: "30 5 * * MON"
  queue: cron
  class: ControlUpload
  args: "rkm_weekly"
  description: rkm calculation weekly process
  rails_envs: development, production, staging
 
#jde_test_import:
#   cron: "25 9 31 * *"
#   queue: cron
#   class: ControlUpload
#   args: "test_import"
#   description: testing
#   rails_envs: development, production, staging
  

# jde_net_sales:
#  cron: "0 4 6 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "monthly_net_sales"
#  description: migration net sales to sales analytic
#  rails_envs: development, production, staging