daily_migration:
  cron: "0 7-18 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "daily_migration"
  description: migrate sales_report
  rails_envs: development, production, staging

send_email:
  cron: "30 09 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "send_mail"
  description: send report upload sales branches
  rails_envs: production

send_email_prev_month:
  cron: "30 09 1-11 * *"
  queue: cron
  class: ControlUpload
  args: "send_mail_previous_month"
  description: send report upload sales branches last month
  rails_envs: production

update_price_list:
  cron: "01 0 * * *"
  queue: cron
  class: ControlUpload
  args: "update_price_list"
  description: update price list
  rails_envs: development, production, staging

check_sales_reports:
  cron: "0 0 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_reports"
  description: check sales_reports
  rails_envs: development, production, staging

check_sales_reports_prev_month:
  cron: "0 0 1-11 * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_reports_prev_month"
  description: check sales_reports
  rails_envs: development, production, staging

check_stock:
  cron: "0 08,12,16 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_stock"
  description: check stock
  rails_envs: development, production, stagings

jde_migration_order:
  cron: "15 10 * * *"
  queue: cron
  class: ControlUpload
  args: "daily_migration_jde"
  description: sales reports jde
  rails_envs: development, production, staging

jde_intransit_to_pos:
  cron: "0 8-21 * * *"
  queue: cron
  class: ControlUpload
  args: "intransit_pos"
  description: intransit jde to point of sales
  rails_envs: development, production, staging

