# daily_migration:
#  cron: "0 7-24 * * 1-7"
#  queue: cron
#  class: ControlUpload
#  args: "daily_migration"
#  description: migrate sales_report
#  rails_envs: development, production, staging

jde_new_item:
  cron: "0 3 * * *"
  queue: cron
  class: ControlUpload
  args: "daily_new_item"
  description: sales reports jde
  rails_envs: development, production, staging

jde_intransit_to_pos:
  cron: "0 8-24 * * *"
  queue: cron
  class: ControlUpload
  args: "intransit_pos"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_sales_items:
  cron: "5 0 * * *"
  queue: cron
  class: ControlUpload
  args: "import_sales_jde"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_beginning_of_month:
  cron: "1 0 * * 0"
  queue: cron
  class: ControlUpload
  args: "import_beginning_of_month"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  

# jde_net_sales:
#  cron: "0 4 6 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "monthly_net_sales"
#  description: migration net sales to sales analytic
#  rails_envs: development, production, staging