send_email:
  cron: "30 08 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "send_mail"
  description: send report upload sales branches
  rails_envs: production
  
update_price_list:
  cron: "01 0 * * *"
  queue: cron
  class: ControlUpload
  args: "update_price_list"
  description: update price list
  rails_envs: development, production, staging

check_sales_reports:
  cron: "30 0 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_reports"
  description: check sales_reports
  rails_envs: development, production, staging