# daily_migration:
#  cron: "0 7-24 * * 1-7"
#  queue: cron
#  class: ControlUpload
#  args: "daily_migration"
#  description: migrate sales_report
#  rails_envs: development, production, staging
  
jde_display_stock:
  cron: "30 17 * * *"
  queue: cron
  class: ControlUpload
  args: "test_display_stocks"
  description: fetching display stock
  rails_envs: development, production, staging
  
jde_weekly_fetch_on_sunday:
  cron: "1 0 * * 0"
  queue: cron
  class: ControlUpload
  args: "sunday_weekly_batch"
  description: fetching item costs and buffer
  rails_envs: development, production, staging

jde_new_item:
  cron: "0 3 * * *"
  queue: cron
  class: ControlUpload
  args: "daily_new_item"
  description: sales reports jde
  rails_envs: development, production, staging

jde_intransit_to_pos:
  cron: "0 8-24 * * *"
  queue: cron
  class: ControlUpload
  args: "intransit_pos"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_sales_items:
  cron: "0 4 * * *"
  queue: cron
  class: ControlUpload
  args: "import_sales_jde"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_beginning_of_week:
  cron: "1 0 * * 1"
  queue: cron
  class: ControlUpload
  args: "import_beginning_of_week"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_stock_hourly:
  cron: "0 7-21 * * *"
  queue: cron
  class: ControlUpload
  args: "import_stock_hourly"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  
jde_import_acc_receivable:
  cron: "0 2 * * *"
  queue: cron
  class: ControlUpload
  args: "import_acc_receivable"
  description: intransit jde to point of sales
  rails_envs: development, production, staging
  

# jde_net_sales:
#  cron: "0 4 6 * * *"
#  queue: cron
#  class: ControlUpload
#  args: "monthly_net_sales"
#  description: migration net sales to sales analytic
#  rails_envs: development, production, staging