send_email:
  cron: "30 09 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "send_mail"
  description: send report upload sales branches
  rails_envs: production

send_email_prev_month:
  cron: "30 09 1-11 * *"
  queue: cron
  class: ControlUpload
  args: "send_mail_previous_month"
  description: send report upload sales branches last month
  rails_envs: production

update_price_list:
  cron: "01 0 * * *"
  queue: cron
  class: ControlUpload
  args: "update_price_list"
  description: update price list
  rails_envs: development, production, staging

check_sales_reports:
  cron: "0 0 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_reports"
  description: check sales_reports
  rails_envs: development, production, staging

check_sales_reports_prev_month:
  cron: "0 0 1-11 * 1-6"
  queue: cron
  class: ControlUpload
  args: "check_reports_prev_month"
  description: check sales_reports
  rails_envs: development, production, staging

daily_migration:
  cron: "12 01 * * 1-6"
  queue: cron
  class: ControlUpload
  args: "daily_migration"
  description: migrate sales_report
  rails_envs: development, production, staging

daily_migration_prev_month:
  cron: "30 12 1-11 * 1-6"
  queue: cron
  class: ControlUpload
  args: "daily_migration_prev_month"
  description: migrate sales_report
  rails_envs: development, production, staging

daily_update_customer:
  cron: "00 21 *s * 1-6"
  queue: cron
  class: ControlUpload
  args: "update_customer"
  description: update customer
  rails_envs: development, production, staging
  
